### ISSUE TITLE
StudyProg.pyが動かない

### ISSUE THREAD

**Issue by haruna-yoshida** [haruna-yoshida/NLP#2]
エラーコード↓

Harunas-MacBook-Air:NLP haruna$ Python3 StudyProg.py
Traceback (most recent call last):
  File "/Users/haruna/Desktop/NLP/StudyProg.py", line 4, in <module>
    import MeCab
  File "/Users/haruna/.pyenv/versions/3.9.0/lib/python3.9/site-packages/MeCab/__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: dlopen(/Users/haruna/.pyenv/versions/3.9.0/lib/python3.9/site-packages/MeCab/_MeCab.cpython-39-darwin.so, 2): Symbol not found: __ZN5MeCab11createModelEPKc
  Referenced from: /Users/haruna/.pyenv/versions/3.9.0/lib/python3.9/site-packages/MeCab/_MeCab.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/haruna/.pyenv/versions/3.9.0/lib/python3.9/site-packages/MeCab/_MeCab.cpython-39-darwin.so

**Comment by TakaoWing** [comment]
隠しフォルダで，見えなかっただけで「.venv」フォルダありました！
VSCodeを開いてターミナルに「.venv/bin/activate」コマンドを打つとこのフォルダ内のpythonの環境に入れて動くはずです！
確認してみて！
ダメな場合，わからない場合はコメントください！

**Comment by haruna-yoshida** [comment]
Permission deniedになりました

**Comment by haruna-yoshida** [comment]
. .venv/bin/activateで解決
